server:
  port: 8001

spring:
  application:
    name: spring-dubbo-provider
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.71.128:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: FN5HW5Y1XQJ742I7

dubbo:
  application:
    name: spring-dubbo-provider
  registry:
    address: nacos://192.168.71.128:8848
  scan:
    base-packages: org.example

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.entities
