server:
  port: 8002

spring:
  application:
    name: spring-dubbo-consumer

dubbo:
  application:
    name: spring-dubbo-consumer
  registry:
#    address: nacos://192.168.71.128:8848
    address: zookeeper://192.168.71.128:2181
  scan:
    base-packages: org.example

